# Final Project

#### Context:
You are hired as a database designer to create a comprehensive database system for OCU's campus library. The library needs to efficiently manage information about books, authors, students, faculty, borrowing, and returning of books. The library serves multiple departments (schools) within the university and needs to keep track of various activities such as book availability, overdue fines, and transaction details.

#### Problem:
Create a Library Management System through the creation and design a relational database for the library. Identify entities and their attributes, define tables, normalize these tables, and create the database in MySQL.

#### Tasks:

**1. Identify Entities and Attributes:**

Identify the main entities involved in the library system (e.g., books, authors, students, faculty, borrowing, returning).
Determine the attributes for each entity (e.g., book ID, title, author name, student ID, name, faculty ID, department, etc.).

**2. Define Tables:**

Create a list of tables based on the identified entities and their attributes.
Determine the primary keys for each table.

**3. Normalize Tables:**

Normalize the tables to eliminate redundancy and improve data integrity.
Identify relationships between different entities and create foreign keys where necessary.

**4. Create the Database in MySQL:**

Using MySQL syntax, create a new database for the library system.
Create tables based on the normalized design, specifying data types, primary keys, and foreign keys.
Insert sample data into the tables to demonstrate the relationships between entities (e.g., books, authors, students, faculty, borrowing records).

**5. Write SQL Queries:**

Write SQL queries to retrieve information from the database, such as:
List all books available in the library.
Find the names of students who have borrowed a specific book.
Calculate the total fines collected by the library.
List all overdue books.

**6. Create a Python CRUD Application:**

Design and implement a Python application that allows users to interact with the MySQL database. You can create functions or classes for each CRUD operation for each table in the database. Here's a general outline of what this component might look like:

* Create (Insert): Write functions to insert new records into the database tables. For example, you can create functions to add new books, authors, students, faculty members, borrowing records, etc.

* Read (Select): Implement functions to retrieve data from the database. You can create functions to fetch information such as a list of all books, book details, student information, borrowing history, overdue books, etc.

* (OPTIONAL) Update: Design functions that allow users to update existing records. For instance, you can create functions to update book information, student records, or borrowing details.

* Delete: Implement functions to delete records from the database when necessary. This could include removing books, deleting student or faculty records, or clearing borrowing history.

**7. Integrate Pandas:**

You can use the Pandas library to make working with data in Python more convenient. For example, you can load query results into Pandas DataFrames, which makes data manipulation and analysis easier. Here's how you can integrate Pandas:

* After running SQL SELECT queries to fetch data, convert the result sets into Pandas DataFrames.

* (OPTIONAL) Utilize Pandas DataFrame operations for data filtering, sorting, and analysis as needed.

* (OPTIONAL) For creating new records (INSERT), you can create Pandas DataFrames with user input and then insert these records into the respective database tables.

In [ ]:
#You are welcome to use your own code for the project or use and use the one below as a foundation
import mysql.connector

# Initialize the MySQL database connection
conn = mysql.connector.connect(
    host="your_host",
    user="your_username",
    password="your_password",
    database="your_database"
)

cursor = conn.cursor()

#CRUD Functions, after a user selects an entity, a parameter will be passed to the table
def create_record(table_name):
    # Write your code to insert a record here
    pass

def read_records(table_name):
    # Write your code to select. (You can integrate PANDAS here)
    pass

def update_record(table_name):
    # Write your code to update record here (optional)
    pass

def delete_record(table_name):
    # Write your code to delete a record here
    pass

def main_menu():
    while True:
        #This menu prints options to CRUD every entity (table) in the database. Manually add every entity you want to CRUD
        print("\nMain Menu:")
        print("1. Students")
        print("2. Instructors")
        print("3. Courses")
        print("4. Exit")

        choice = input("Select an option: ")
        
        # The parameter selected should be the name of the table in the database. This parameter will be sent to the CRUD functions
        if choice == '1':
            table_menu("Students")
        elif choice == '2':
            table_menu("Instructors")
        elif choice == '3':
            table_menu("Courses")
        elif choice == '4':
            break
        else:
            print("Invalid option. Please try again.")

def table_menu(table_name):
    while True:
        print(f"\n{table_name} Menu:")
        print("1. Create")
        print("2. Read")
        print("3. Update")
        print("4. Delete")
        print("5. Back")

        choice = input("Select an action: ")

        if choice == '1':
            create_record(table_name)
        elif choice == '2':
            read_records(table_name)
        elif choice == '3':
            update_record(table_name)
        elif choice == '4':
            delete_record(table_name)
        elif choice == '5':
            break
        else:
            print("Invalid action. Please try again.")

if __name__ == '__main__':
    main_menu()

# Close the database connection when done
cursor.close()
conn.close()

## Project Rubric: Library Management System
### Database Design (20 points):

#### Entities and Attributes (10 points):

 * Excellent (10 pts): Accurately identifies main entities and their attributes with a comprehensive list.
 * Good (8 pts): Identifies most entities and attributes but may miss some or have minor omissions.
 * Satisfactory (6 pts): Identifies some entities and attributes but with significant omissions.
 * Poor (0 pts): Fails to identify entities and attributes adequately.

#### Tables and Primary Keys (15 points):

 * Excellent (15 pts): Defines tables based on entities and attributes, accurately determines primary keys.
 * Good (12 pts): Defines most tables and primary keys but may have minor issues.
 * Satisfactory (9 pts): Defines some tables and primary keys but with significant issues.
 * Poor (0 pts): Fails to define tables and primary keys.

#### Normalization and Relationships (10 points):

 * Excellent (10 pts): Successfully normalizes tables to eliminate redundancy and defines relationships.
 * Good (8 pts): Normalizes most tables but may have minor issues or gaps in relationships.
 * Satisfactory (6 pts): Normalizes some tables but with significant issues in redundancy and relationships.
 * Poor (0 pts): No normalization or relationship definitions.

#### MySQL Database Creation (5 points):

 * Excellent (5 pts): Successfully creates a MySQL database with tables, data types, primary keys, and relationships.
 * Good (4 pts): Creates the database and tables but with minor issues.
 * Satisfactory (3 pts): Creates the database and tables with significant issues.
 * Poor (0 pts): Fails to create the MySQL database.


### Python CRUD Application (40 points):

#### Insert Implementation (15 points):

 * Excellent (15 pts): CRUD functions for creating records work effectively.
 * Good (12 pts): Inserts records with minor issues.
 * Satisfactory (9 pts): Inserts records but with significant issues.
 * Poor (0 pts): Fails to implement record insertion.

#### Read Implementation with Pandas Integration (15 points):

 * Excellent (15 pts): Successfully integrates Pandas for data retrieval, filtering, and analysis in the read operation.
 * Good (12 pts): Integrates Pandas effectively but with minor issues.
 * Satisfactory (9 pts): Attempts Pandas integration but with significant issues.
 * Poor (0 pts): No Pandas integration in the read operation.

#### Delete Implementation (10 points):

 * Excellent (10 pts): CRUD functions for deleting records work effectively.
 * Good (8 pts): Deletes records with minor issues.
 * Satisfactory (6 pts): Deletes records but with significant issues.
 * Poor (0 pts): Fails to implement record deletion.

<table>
  <tr>
    <th>Criteria</th>
    <th>Excellent</th>
    <th>Good</th>
    <th>Satisfactory</th>
    <th>Poor</th>
  </tr>
  <tr>
    <td><strong>Database Design</strong></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>1. Entities and Attributes</td>
    <td>10 pts</td>
    <td>8 pts</td>
    <td>6 pts</td>
    <td>0 pts</td>
  </tr>
  <tr>
    <td>2. Tables and Primary Keys</td>
    <td>15 pts</td>
    <td>12 pts</td>
    <td>9 pts</td>
    <td>0 pts</td>
  </tr>
  <tr>
    <td>3. Normalization and Relationships</td>
    <td>10 pts</td>
    <td>8 pts</td>
    <td>6 pts</td>
    <td>0 pts</td>
  </tr>
  <tr>
    <td>4. MySQL Database Creation</td>
    <td>5 pts</td>
    <td>4 pts</td>
    <td>3 pts</td>
    <td>0 pts</td>
  </tr>
  
  <tr>
    <td><strong>Python CRUD Application</strong></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>7. Insert Implementation</td>
    <td>15 pts</td>
    <td>12 pts</td>
    <td>9 pts</td>
    <td>0 pts</td>
  </tr>
  <tr>
    <td>8. Read Implementation (with Pandas Integration)</td>
    <td>15 pts</td>
    <td>12 pts</td>
    <td>9 pts</td>
    <td>0 pts</td>
  </tr>
  <tr>
    <td>9. Delete Implementation</td>
    <td>10 pts</td>
    <td>8 pts</td>
    <td>6 pts</td>
    <td>0 pts</td>
  </tr>
  
</table>